name: Maven Build and Bash Script
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn install

      - name: Run Bash Script
        run: |
          chmod +x src/helloworld.sh
          cd src && ./helloworld.sh
